# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# Copy source
COPY src ./src

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build

# No port exposure (stdio)

# Default command
CMD ["node", "dist/index.js"]
