# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install deps
COPY package.json tsconfig.json ./
RUN npm install

# Copy source and build
COPY src ./src
RUN npm run build

# Production stage
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Ensure local binaries are in PATH
ENV PATH /app/node_modules/.bin:$PATH

# Start server
ENTRYPOINT ["node", "dist/index.js"]
